// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fcnnls_c
arma::mat fcnnls_c(const arma::mat& C, const arma::mat& A);
RcppExport SEXP _linseed_fcnnls_c(SEXP CSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(fcnnls_c(C, A));
    return rcpp_result_gen;
END_RCPP
}
// fcnnls_sum_to_one
arma::mat fcnnls_sum_to_one(const arma::mat& C, const arma::mat& A, double delta);
RcppExport SEXP _linseed_fcnnls_sum_to_one(SEXP CSEXP, SEXP ASEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(fcnnls_sum_to_one(C, A, delta));
    return rcpp_result_gen;
END_RCPP
}
// pairwiseR2
arma::mat pairwiseR2(const arma::mat& X);
RcppExport SEXP _linseed_pairwiseR2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwiseR2(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_linseed_fcnnls_c", (DL_FUNC) &_linseed_fcnnls_c, 2},
    {"_linseed_fcnnls_sum_to_one", (DL_FUNC) &_linseed_fcnnls_sum_to_one, 3},
    {"_linseed_pairwiseR2", (DL_FUNC) &_linseed_pairwiseR2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_linseed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
