# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcnnls_c <- function(C, A) {
    .Call('_linseed_fcnnls_c', PACKAGE = 'linseed', C, A)
}

fcnnls_sum_to_one <- function(C, A, delta = 1) {
    .Call('_linseed_fcnnls_sum_to_one', PACKAGE = 'linseed', C, A, delta)
}

pairwiseR2 <- function(X) {
    .Call('_linseed_pairwiseR2', PACKAGE = 'linseed', X)
}

